name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: |
        ./gradlew clean
        ./gradlew tasks --group="build"
        echo "=== Starting Debug Build ==="
        ./gradlew assembleDebug --console=plain --info
        
    - name: Debug Build Info
      run: |
        echo "=== Gradle Properties ==="
        ./gradlew properties
        echo "=== Gradle Home ==="
        echo $GRADLE_HOME
        echo "=== Android Home ==="
        echo $ANDROID_HOME
        echo "=== Project Structure ==="
        ls -la
        echo "=== Build Directory Content ==="
        ls -R app/build/ || true
        echo "=== Gradle Files ==="
        cat settings.gradle
        cat app/build.gradle
        echo "=== Find APK ==="
        find . -type f -name "*.apk" 2>/dev/null || true
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: |
          app/build/outputs/apk/debug/*.apk
          build/outputs/apk/debug/*.apk