jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-disabled: true
      - name: Build with Gradle
        run: |
          ./gradlew clean
          ./gradlew tasks --all
          echo "=== Starting Debug Build ==="
          ./gradlew assembleDebug --console=plain --info --stacktrace
          echo "=== Build Complete ==="
          echo "=== Checking Build Directory ==="
          ls -la app/build/
          echo "=== Checking Outputs Directory ==="
          ls -la app/build/outputs/ || true
      - name: Check build outputs
        run: |
          echo "=== APK Directory Structure ==="
          ls -R app/build/outputs/ || true
          echo "=== Find APK files ==="
          find . -name "*.apk" || true
      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk 